<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Master Data_css-1e3tf61</name>
   <tag></tag>
   <elementGuidId>1ce9e0b3-3c8c-4e6d-b2c0-c79fc355fb61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='configurationTab']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#configurationTab > div.css-1e3tf61</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e5a8dd4-b1a5-4d66-b8eb-c2006a2806d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1e3tf61</value>
      <webElementGuid>ca1e2be4-96cc-4cf1-a4e9-348fda728912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;configurationTab&quot;)/div[@class=&quot;css-1e3tf61&quot;]</value>
      <webElementGuid>471bc904-ea65-4368-9eb6-59b2993b7bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>3c6601d5-93fa-42f6-a34b-65ac9c102541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='configurationTab']/div</value>
      <webElementGuid>11914c0f-4602-440d-94c7-67d172105632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Data'])[2]/following::div[2]</value>
      <webElementGuid>e0cdf794-bdcc-4871-bbfb-89f5ac8dee0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturing'])[1]/following::div[5]</value>
      <webElementGuid>b5836075-7620-4c8b-a75b-8beb4b2c0097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/preceding::div[1]</value>
      <webElementGuid>bd76b892-1197-4a0b-826e-c09a4420de15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account'])[1]/preceding::div[3]</value>
      <webElementGuid>088c7822-0982-4350-a220-69c919a8fdfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div</value>
      <webElementGuid>c3a840e8-5973-4a91-91fb-c8aa1e33d627</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
