<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hierarchy Browser_css-1e3tf61</name>
   <tag></tag>
   <elementGuidId>ca347a44-4618-4ee7-81eb-e3d2877ebbd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='codeTreasurerTab']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#codeTreasurerTab > div.css-1e3tf61</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dbc5fe04-9a02-4383-8e43-1d3adead229f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1e3tf61</value>
      <webElementGuid>f24a1e2f-f274-4bde-b3ea-9bc40e13bf8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeTreasurerTab&quot;)/div[@class=&quot;css-1e3tf61&quot;]</value>
      <webElementGuid>8f1d25c3-a526-446a-abce-b582d2ac0437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_osapiens QA Portal/iframe_FH_webbundlediv904_1</value>
      <webElementGuid>9cf34c15-88df-4113-9ce5-9dd48f16fdd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='codeTreasurerTab']/div</value>
      <webElementGuid>30718325-cec8-4df3-b909-1c6996f07e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hierarchy Browser'])[2]/following::div[2]</value>
      <webElementGuid>0fe6deac-8d95-4044-8e5f-427da52f114b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History Browser'])[1]/following::div[5]</value>
      <webElementGuid>5edcd493-e333-490c-b4e1-79dd1c7d4127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code Treasurer'])[1]/preceding::div[1]</value>
      <webElementGuid>db543b1b-96af-4117-bebf-58989869a463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturing'])[1]/preceding::div[3]</value>
      <webElementGuid>e3fa98b2-9a19-441a-bf2e-cecf828e91e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>52b4a49f-23de-4702-989b-6aebbd55a55a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
