<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_qcbdr1DE441987_css-1w3nhzv</name>
   <tag></tag>
   <elementGuidId>f4883012-a978-427e-9202-31fcb2e41e4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portal-container']/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1w3nhzv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d475370c-b4f2-407f-a602-be05c30a5637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1w3nhzv</value>
      <webElementGuid>90102440-8f09-4f3d-8bf7-1a48c584ae38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portal-container&quot;)/div[@class=&quot;css-6o8d2m&quot;]/div[@class=&quot;css-1gftt0e&quot;]/div[@class=&quot;css-1w3nhzv&quot;]</value>
      <webElementGuid>a322e8ab-397a-444b-9101-0b65973a6493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>aceb8fb0-ed0f-412e-9a21-9896fa8db893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal-container']/div/div/div[3]</value>
      <webElementGuid>29d1c62b-e837-4e61-8919-98b12a837f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[3]</value>
      <webElementGuid>23326250-b70a-4328-ba79-cb5da3f96b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
