<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Configuration_a</name>
   <tag></tag>
   <elementGuidId>ddace29d-429b-49e7-93e3-ece331abaacc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accountTab > div.css-1e3tf61 > svg > g.b > path.a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>75e311ff-42b2-419e-9b7d-afac96176410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f706a101-b63a-451a-9473-cd2f55e20c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M18,6a6,6,0,1,1-6,6,6,6,0,0,1,6-6m0,15c6.63,0,12,2.685,12,6v3H6V27C6,23.685,11.37,21,18,21Z</value>
      <webElementGuid>2cbaee18-422c-430d-92a5-e2f4f42bc2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(-6 -6)</value>
      <webElementGuid>dc4b6f34-2c64-447c-ab59-bfa68f0f3727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountTab&quot;)/div[@class=&quot;css-1e3tf61&quot;]/svg[1]/g[@class=&quot;b&quot;]/path[@class=&quot;a&quot;]</value>
      <webElementGuid>c05f1acf-c251-410a-b877-0a5ab51a2120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/1.1.3/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>1a17333c-5a8b-4f9a-8392-f63043e5f2cd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
