<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Code Treasurer_factory</name>
   <tag></tag>
   <elementGuidId>0a3f208c-63a3-48a6-89d2-261714fc220d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//path[@id = 'factory']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#factory</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>3b66e039-e6c3-4add-9a83-b70576a4f759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>factory</value>
      <webElementGuid>bd056748-3d99-4cde-bee0-ae9f2b307a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M4.8,21.6V24H9.6V21.6H4.8m0-4.8v2.4h12V16.8H4.8M12,21.6V24h4.8V21.6H12m7.2-4.8v2.4H24V16.8H19.2m0,4.8V24H24V21.6H19.2M2.4,26.4V9.6l6,4.8V9.6l6,4.8V9.6l6,4.8,1.2-12h3.6l1.2,12v12Z</value>
      <webElementGuid>b513e922-27fa-4178-a6ca-4c4aca0acc84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(21.6 13.38)</value>
      <webElementGuid>4b52e58f-dd3f-4af9-9a18-27d7578b4062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;factory&quot;)</value>
      <webElementGuid>ef63b0d3-bcf1-4b0b-9527-aa695a396567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Object 1.1.2/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>71375880-498a-4dbc-ba24-da18466cb692</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//path[@id = 'factory']</value>
      <webElementGuid>53c53451-f518-4b9f-ac15-e13cd2d5a95a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
