<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path_Configuration_a</name>
   <tag></tag>
   <elementGuidId>425a705d-f610-4203-b16a-3015d2b3b57b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accountTab > div.css-1e3tf61 > svg > g.b > path.a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>987af290-97dd-4e85-8656-e63dd65d9cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba29bf0e-c6ca-4fcc-87c0-1ee1cab6a0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M18,6a6,6,0,1,1-6,6,6,6,0,0,1,6-6m0,15c6.63,0,12,2.685,12,6v3H6V27C6,23.685,11.37,21,18,21Z</value>
      <webElementGuid>a12321a6-f5b6-4111-949f-c4320a827ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>translate(-6 -6)</value>
      <webElementGuid>2dbee1f3-e0e3-49cd-9c43-b1e38f553164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accountTab&quot;)/div[@class=&quot;css-1e3tf61&quot;]/svg[1]/g[@class=&quot;b&quot;]/path[@class=&quot;a&quot;]</value>
      <webElementGuid>92a8eaa8-5ba9-4ea9-b824-727b4cf212b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Object 1.1.2/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>c825166f-b1c1-4304-8734-e07f221aead5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
