<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AGGREGATE</name>
   <tag></tag>
   <elementGuidId>08e252b2-9193-463a-af68-f185726a40d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='portal-container']/div[3]/div[2]/div[3]/div[2]/table/tbody/tr/td/span/span/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.css-hoe9xz</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f091a719-30cb-4aa3-906e-7dea26788dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-hoe9xz</value>
      <webElementGuid>6673a220-dc79-493d-813c-8e7f30312a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AGGREGATE</value>
      <webElementGuid>90eab5fe-32ea-438a-b69f-8352536ed870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;portal-container&quot;)/div[@class=&quot;css-19brph0&quot;]/div[@class=&quot;css-10sg1fp&quot;]/div[@class=&quot;css-1jptfp8&quot;]/div[@class=&quot;MuiTableContainer-root css-kge0eu&quot;]/table[@class=&quot;MuiTable-root MuiTable-stickyHeader css-lkld8c&quot;]/tbody[@class=&quot;MuiTableBody-root css-1xnox0e&quot;]/tr[@class=&quot;MuiTableRow-root css-yc7f6w&quot;]/td[@class=&quot;MuiTableCell-root MuiTableCell-body MuiTableCell-alignLeft MuiTableCell-sizeMedium css-1kll36z&quot;]/span[1]/span[@class=&quot;css-aibifd&quot;]/div[@class=&quot;css-x1sij0&quot;]/span[@class=&quot;css-hoe9xz&quot;]</value>
      <webElementGuid>e04a3d07-3896-42a9-8533-c050a01575ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/1.2.1/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>ad23b3eb-d030-4cdf-8697-bb57bf172331</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portal-container']/div[3]/div[2]/div[3]/div[2]/table/tbody/tr/td/span/span/div/span</value>
      <webElementGuid>7ac9497d-40ea-4444-bf4a-f913bc2946d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resent'])[1]/following::span[3]</value>
      <webElementGuid>ebf76bd4-2d0e-4e86-80fd-a6dac9ccdd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle'])[1]/following::span[3]</value>
      <webElementGuid>a2599a35-63ca-4d5d-98a8-57c3fecd9399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REJECTED'])[1]/preceding::span[1]</value>
      <webElementGuid>1405470a-de31-472a-90ea-d8eb726f8e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='osapiens 1'])[1]/preceding::span[5]</value>
      <webElementGuid>7af15c27-3703-42a2-89c8-8aa95ad4d228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AGGREGATE']/parent::*</value>
      <webElementGuid>9a63f57d-f9b6-4964-9c6f-0c0cbf06908c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>c89adb1f-ceba-4e80-b926-efaf72765f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'AGGREGATE' or . = 'AGGREGATE')]</value>
      <webElementGuid>e5f2d925-f3a2-4c8e-a7df-13c2f571d3e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
