<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hierarchy Browser_css-1e3tf61</name>
   <tag></tag>
   <elementGuidId>2cb675b4-20e4-46b8-8199-bc5915cefffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='codeTreasurerTab']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#codeTreasurerTab > div.css-1e3tf61</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1d93e044-f378-49e4-b03d-0bf9a8900d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1e3tf61</value>
      <webElementGuid>3af575e3-e2af-47af-846f-5fe412e49e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;codeTreasurerTab&quot;)/div[@class=&quot;css-1e3tf61&quot;]</value>
      <webElementGuid>da692f10-f8b9-4956-84d9-e6076123f348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/1.1.2/Page_osapiens QA Portal/iframe_FH_webbundlediv904</value>
      <webElementGuid>cee3bcaa-a901-491a-af1e-b49b9d0c231e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='codeTreasurerTab']/div</value>
      <webElementGuid>91f845a1-5696-4244-83ad-abd205d2122c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hierarchy Browser'])[2]/following::div[2]</value>
      <webElementGuid>5b177e2e-8032-4cf1-921a-16bff42513d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History Browser'])[1]/following::div[5]</value>
      <webElementGuid>f1468087-8384-4736-a9d6-f30ef521b1d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code Treasurer'])[1]/preceding::div[1]</value>
      <webElementGuid>3eb626bd-c6bd-41c7-b989-407ec19cdb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturing'])[1]/preceding::div[3]</value>
      <webElementGuid>91304b2b-791e-4358-9c18-d315dba58b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>2a193680-e0c8-41b3-a30b-e613c954e4da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
